# name of the workflow
name: Github_tests

# when the workflow should be used
on:
    # specify to run on pushes and pull requests
    - push
    - pull_request

# Outline the jobs to be performed within this workflow
jobs:
    # This job is only going to run a single job called test
    test:
        # Specify the OS system(s) to run the job on
        runs-on: ubuntu-20.04
        
        # Specify the strategy to use        
        strategy:
            matrix:
                python-version: [3.8, 3.9, 3.10]
                
        # Outline the steps which the job will perform    
        steps:
            - name: Checkout code
                uses: actions/checkout@v3
            
            - name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}
                    
            - name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install --upgrade tox setuptools wheel tox-gh-actions
            
            - name: Test with tox
                run: tox
